spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/admin_db?createDatabaseIfNotExist=true
    username: shashank
    password: Shashank@123
  cloud:
    openfeign:
      micrometer:
        enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: admin-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: org.team11.tickebook.adminservice.kafka.UserCreatedEvent
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/

server:
  port: 8080
jwt:
  secret: tickebook_auth_jwt_super_secure_secret_2026_value
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env,loggers

  endpoint:
    health:
      show-details: always

  tracing:
    sampling:
      probability: 1.0   # trace all requests
    propagation:
      type: b3

  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
logging:
  level:
    zipkin2: DEBUG
    org.springframework.web.client: DEBUG
    io.micrometer.tracing: DEBUG
  pattern:
    level: "%5p [${spring.application.name},%X{traceId},%X{spanId}]"