server:
  port: 8080

spring:
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
          routes:

            - id: movie-service
              uri: lb://MOVIE-SERVICE
              predicates:
                - Path=/api/movies/**

            - id: consumer-service
              uri: lb://CONSUMER-SERVICE
              predicates:
                - Path=/api/bookings/**,/api/booking-seats/**,/api/tickets/**

            - id: show-service
              uri: lb://SHOW-SERVICE
              predicates:
                - Path=/api/shows/**

            - id: theatre-service
              uri: lb://THEATRE-SERVICE
              predicates:
                - Path=/api/screens/**,/api/seats/**,/api/theatres/**,/api/owner/**

            - id: admin-service
              uri: lb://ADMIN-SERVICE
              predicates:
                - Path=/api/theatre-approval-requests/**,/api/role-approval-requests/**

            - id: auth-service-public
              uri: lb://AUTH-SERVICE
              predicates:
                - Path=/auth/**,/api/user/**

            - id: payment-service
              uri: lb://PAYMENT-SERVICE
              predicates:
                - Path=/payments/**

            - id: monitoring-service
              uri: lb://management-service
              predicates:
                - Path=/metrics/**
              filters:
                - StripPrefix=1

            - id: auth-service-swagger
              uri: lb://AUTH-SERVICE
              predicates:
                - Path=/auth-service-swagger/**
              filters:
                - RewritePath=/auth-service-swagger/(?<segment>.*), /${segment}

            - id: admin-service-swagger
              uri: lb://ADMIN-SERVICE
              predicates:
                - Path=/swagger/admin-service/**
              filters:
                - RewritePath=/swagger/admin-service/(?<segment>.*), /${segment}

            - id: consumer-service-swagger
              uri: lb://CONSUMER-SERVICE
              predicates:
                - Path=/swagger/consumer-service/**
              filters:
                - RewritePath=/swagger/consumer-service/(?<segment>.*), /${segment}
springdoc:
  swagger-ui:
    urls:
      - name: auth-service
        url: /auth-service-swagger/v3/api-docs
      - name: admin-service
        url: /swagger/admin-service/v3/api-docs
      - name: consumer-service
        url: /swagger/consumer-service/v3/api-docs
    config-url: /v3/api-docs/swagger-config
  api-docs:
    enabled: true
eureka:
  client:
    registry-fetch-interval-seconds: 5
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

jwt:

  secret: tickebook_auth_jwt_super_secure_secret_2026_value
