server:
  port: 8080

spring:
  cloud:
    loadbalancer:
      cache:
        enabled: true
    gateway:
      server:
        webflux:
          httpclient:
            connect-timeout: 5000
            response-timeout: 30s
          globalcors:
            cors-configurations:
              '[/**]':
                allowedOrigins:
                  - http://localhost:8080
                allowedMethods:
                  - GET
                  - POST
                  - PUT
                  - DELETE
                  - OPTIONS
                allowedHeaders: "*"
                allowCredentials: true
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
          routes:

            - id: movie-service
              uri: lb://MOVIE-SERVICE
              predicates:
                - Path=/api/movies/**
              filters:
                - name: CircuitBreaker
                  args:
                    name: globalCircuitBreaker
                    fallbackUri: forward:/fallback

            - id: consumer-service
              uri: lb://CONSUMER-SERVICE
              predicates:
                - Path=/api/bookings/**,/api/booking-seats/**,/api/tickets/**
              filters:
                - name: CircuitBreaker
                  args:
                    name: globalCircuitBreaker
                    fallbackUri: forward:/fallback

            - id: show-service
              uri: lb://SHOW-SERVICE
              predicates:
                - Path=/api/shows/**
              filters:
                - name: CircuitBreaker
                  args:
                    name: globalCircuitBreaker
                    fallbackUri: forward:/fallback

            - id: theatre-service
              uri: lb://THEATRE-SERVICE
              predicates:
                - Path=/api/screens/**,/api/seats/**,/api/theatres/**,/api/owner/**
              filters:
                - name: CircuitBreaker
                  args:
                    name: globalCircuitBreaker
                    fallbackUri: forward:/fallback

            - id: admin-service
              uri: lb://ADMIN-SERVICE
              predicates:
                - Path=/api/theatre-approval-requests/**,/api/role-approval-requests/**
              filters:
                - name: CircuitBreaker
                  args:
                    name: globalCircuitBreaker
                    fallbackUri: forward:/fallback

            - id: auth-service-public
              uri: lb://AUTH-SERVICE
              predicates:
                - Path=/auth/**,/api/user/**
              filters:
                - name: CircuitBreaker
                  args:
                    name: globalCircuitBreaker
                    fallbackUri: forward:/fallback

            - id: payment-service
              uri: lb://PAYMENT-SERVICE
              predicates:
                - Path=/payments/**
              filters:
                - name: CircuitBreaker
                  args:
                    name: globalCircuitBreaker
                    fallbackUri: forward:/fallback

            - id: monitoring-service
              uri: lb://management-service
              predicates:
                - Path=/metrics/**
              filters:
                - StripPrefix=1
                - name: CircuitBreaker
                  args:
                    name: globalCircuitBreaker
                    fallbackUri: forward:/fallback

            - id: auth-service-swagger
              uri: lb://AUTH-SERVICE
              predicates:
                - Path=/auth-service-swagger/**
              filters:
                - RewritePath=/auth-service-swagger/(?<segment>.*), /${segment}

            - id: admin-service-swagger
              uri: lb://ADMIN-SERVICE
              predicates:
                - Path=/swagger/admin-service/**
              filters:
                - RewritePath=/swagger/admin-service/(?<segment>.*), /${segment}

            - id: consumer-service-swagger
              uri: lb://CONSUMER-SERVICE
              predicates:
                - Path=/swagger/consumer-service/**
              filters:
                - RewritePath=/swagger/consumer-service/(?<segment>.*), /${segment}

            - id: movie-service-swagger
              uri: lb://MOVIE-SERVICE
              predicates:
                - Path=/swagger/movie-service/**
              filters:
                - RewritePath=/swagger/movie-service/(?<segment>.*), /${segment}

            - id: show-service-swagger
              uri: lb://SHOW-SERVICE
              predicates:
                - Path=/swagger/show-service/**
              filters:
                - RewritePath=/swagger/show-service/(?<segment>.*), /${segment}
            - id: theatre-service-swagger
              uri: lb://THEATRE-SERVICE
              predicates:
                - Path=/swagger/theatre-service/**
              filters:
                - RewritePath=/swagger/theatre-service/(?<segment>.*), /${segment}
springdoc:
  swagger-ui:
    urls:
      - name: auth-service
        url: /auth-service-swagger/v3/api-docs
      - name: admin-service
        url: /swagger/admin-service/v3/api-docs
      - name: consumer-service
        url: /swagger/consumer-service/v3/api-docs
      - name: movie-service
        url: /swagger/movie-service/v3/api-docs
      - name: show-service
        url: /swagger/show-service/v3/api-docs
      - name: theatre-service
        url: /swagger/theatre-service/v3/api-docs
    config-url: /v3/api-docs/swagger-config
  api-docs:
    enabled: true
eureka:
  client:
    registry-fetch-interval-seconds: 5
    initial-instance-info-replication-interval-seconds: 5
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/

jwt:
  secret: tickebook_auth_jwt_super_secure_secret_2026_value
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env,loggers

  endpoint:
    health:
      show-details: always

  tracing:
    sampling:
      probability: 1.0   # trace all requests

  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    io.github.resilience4j: DEBUG
  pattern:
    level: "%5p [${spring.application.name},%X{traceId},%X{spanId}]"
resilience4j:
  circuitbreaker:
    instances:
      globalCircuitBreaker:
        minimumNumberOfCalls: 5
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
  recordExceptions:
    - java.io.IOException
    - java.util.concurrent.TimeoutException
    - org.springframework.web.server.ResponseStatusException
    - reactor.netty.http.client.PrematureCloseException

  ignoreExceptions:
    - org.springframework.web.server.ServerWebInputException
  timelimiter:
    instances:
      globalCircuitBreaker:
        timeoutDuration: 30s