server:
  port: 8080
spring:
  cloud:
    openfeign:
      circuitbreaker:
        enabled: false
  main:
    lazy-initialization: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: Shashank@123
    url: jdbc:mysql://mysql:3306/auth_db?createDatabaseIfNotExist=true
    username: shashank
  jpa:
    hibernate:
      ddl-auto: update
  kafka:
    bootstrap-servers: kafka:9092
    admin:
      auto-create: true
      fail-fast: false
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 3
      properties:
        spring.json.add.type.headers: false
        max.block.ms: 60000
        delivery.timeout.ms: 120000
        request.timeout.ms: 30000
    properties:
      # Slow down reconnection attempts
      reconnect.backoff.ms: 5000
      reconnect.backoff.max.ms: 30000
      retry.backoff.ms: 5000

      # Reduce metadata refresh spam
      metadata.max.age.ms: 600000
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/
#  instance:
#    prefer-ip-address: true
jwt:
  secret: tickebook_auth_jwt_super_secure_secret_2026_value
default:
  admin:
    email: admin@tickebook.com
    password: admin123
logging:
  level:
    root: INFO
    org.springframework: WARN
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE
    org.team11.tickebook: DEBUG   # your base package
resilience4j:
  circuitbreaker:
    instances:
      MAIL-SERVER:
        minimumNumberOfCalls: 5
        slidingWindowSize: 10
        failureRateThreshold: 50
  timelimiter:
    instances:
      MAIL-SERVER:
        timeoutDuration: 30s