spring:
  cloud:
    openfeign:
      circuitbreaker:
        enabled: false
      micrometer:
        enabled: true
  application:
    name: consumer-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: Shashank@123
    url: jdbc:mysql://mysql:3306/consumer_db?createDatabaseIfNotExist=true
    username: shashank
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    show-sql: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env,loggers
  endpoint:
    health:
      show-details: always
  tracing:
    export:
      zipkin:
        endpoint: http://zipkin:9411/api/v2/spans
    sampling:
      probability: 1.0   # trace all requests
    propagation:
      type: B3
server:
  port: 8080
logging:
  pattern:
    level: "%5p [${spring.application.name},%X{traceId},%X{spanId}]"
resilience4j:
  circuitbreaker:
    instances:
      payment-service:
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
      SHOW-SERVICE:
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s