spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: Shashank@123
    url: jdbc:mysql://mysql:3306/show_db?createDatabaseIfNotExist=true
    username: shashank
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    show-sql: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/
server:
  port: 8080
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env,loggers
  endpoint:
    health:
      show-details: always
  tracing:
    export:
      zipkin:
        endpoint: http://zipkin:9411/api/v2/spans
    sampling:
      probability: 1.0   # trace all requests
    propagation:
      type: B3
logging:
  pattern:
    level: "%5p [${spring.application.name},%X{traceId},%X{spanId}]"